# -*- coding: utf-8 -*-
"""DBMS_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JULfsqZWC-RVmP46brAqKu28O5QeMae3
"""

import random

# Set the seed for reproducibility (optional)
random.seed(42)

# Generate 100 random customer IDs
customer_ids = [random.randint(1000, 9999) for _ in range(100)]

# Print the generated customer IDs
print(customer_ids)

import random
import pandas as pd
from faker import Faker

# Install Faker if not already installed
!pip install faker

# Set seed for reproducibility
random.seed(42)

# Initialize Faker
faker = Faker()

# Generate dummy data for customers
num_customers = 100

customer_ids = [i + 1 for i in range(num_customers)]
names = [faker.name() for _ in range(num_customers)]
addresses = [faker.address() for _ in range(num_customers)]
dobs = [faker.date_of_birth(minimum_age=18, maximum_age=65) for _ in range(num_customers)]
contact_nos = [faker.phone_number() for _ in range(num_customers)]
email_ids = [faker.email() for _ in range(num_customers)]
genders = [random.choice(['Male', 'Female']) for _ in range(num_customers)]
balances = [round(random.uniform(1000, 10000), 2) for _ in range(num_customers)]
credit_scores = [random.randint(300, 850) for _ in range(num_customers)]
loan_status = [random.choice(['Approved', 'Pending', 'Rejected']) for _ in range(num_customers)]

# Create a DataFrame from the generated data
df = pd.DataFrame({
    'CustomerID': customer_ids,
    'Name': names,
    'Address': addresses,
    'DOB': dobs,
    'ContactNo': contact_nos,
    'EmailID': email_ids,
    'Gender': genders,
    'Balance': balances,
    'CreditScore': credit_scores,
    'LoanStatus': loan_status
})

# Display the first few rows of the generated dataset
df.head()

import random
import pandas as pd
from faker import Faker

# Install Faker if not already installed
!pip install faker

# Set seed for reproducibility
random.seed(42)

# Initialize Faker
faker = Faker()

# Generate dummy data for customers
num_customers = 100

customer_ids = [i + 1 for i in range(num_customers)]
names = [faker.name() for _ in range(num_customers)]
addresses = [faker.address() for _ in range(num_customers)]
dobs = [faker.date_of_birth(minimum_age=18, maximum_age=65) for _ in range(num_customers)]
contact_nos = [faker.phone_number() for _ in range(num_customers)]
email_ids = [faker.email() for _ in range(num_customers)]
genders = [random.choice(['Male', 'Female']) for _ in range(num_customers)]
balances = [round(random.uniform(1000, 10000), 2) for _ in range(num_customers)]
credit_scores = [random.randint(300, 850) for _ in range(num_customers)]
loan_status = [random.choice(['Approved', 'Pending', 'Rejected']) for _ in range(num_customers)]

# Create a DataFrame from the generated data
df = pd.DataFrame({
    'CustomerID': customer_ids,
    'Name': names,
    'Address': addresses,
    'DOB': dobs,
    'ContactNo': contact_nos,
    'EmailID': email_ids,
    'Gender': genders,
    'Balance': balances,
    'CreditScore': credit_scores,
    'LoanStatus': loan_status
})

# Display the first few rows of the generated dataset
df.head()

# Save the DataFrame to a CSV file
output_filename = "bank_customer_data.csv"
df.to_csv(output_filename, index=False)

# Provide a download link for the CSV file
from google.colab import files
files.download(output_filename)

pip install faker